# Generated by Django 3.2.5 on 2021-08-18 12:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devices", "0008_auto_20210818_1206"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=200)),
                ("is_enabled", models.BooleanField(default=True)),
                ("send_notification", models.BooleanField(default=True)),
                ("notification_topic", models.CharField(max_length=200)),
                ("notification_message", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata_field", models.CharField(max_length=255, null=True)),
                ("metadata_trigger_value", models.CharField(max_length=255, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("Less than", "Less than"),
                            ("Less than or equal to", "Less than or equal to"),
                            ("Equal to", "Equal to"),
                            ("Greater than or equal to", "Greater than or equal to"),
                            ("Greater than", "Greater than"),
                            ("Not equal to", "Not equal to"),
                        ],
                        default="Equal to",
                        max_length=100,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
