# Generated by Django 3.2.5 on 2021-09-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtriggerlog'),
        ('notifications', '0002_auto_20210817_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='trigger_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventtriggerlog'),
        ),
    ]
