# Generated by Django 3.2.5 on 2021-09-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_auto_20210910_0745"),
        ("notifications", "0003_notification_trigger_log"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification",
            new_name="NotificationLog",
        ),
    ]
