# Generated by Django 3.2.5 on 2021-08-28 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_devicestate'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descriptive name for this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable event triggers?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notification_message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Message you will receive when event is triggered'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notification_topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject for message when event is triggered'),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='Send notifications when triggered?'),
        ),
        migrations.AlterField(
            model_name='eventtrigger',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable this trigger?'),
        ),
        migrations.AlterField(
            model_name='eventtrigger',
            name='metadata_field',
            field=models.CharField(max_length=255, null=True, verbose_name='Data field for event trigger'),
        ),
        migrations.AlterField(
            model_name='eventtrigger',
            name='metadata_trigger_value',
            field=models.CharField(max_length=255, null=True, verbose_name='Data field value for trigger'),
        ),
        migrations.AlterField(
            model_name='eventtrigger',
            name='trigger_type',
            field=models.CharField(choices=[('Equal to', 'Equal to'), ('Not equal to', 'Not equal to'), ('Less than', 'Less than'), ('Less than or equal to', 'Less than or equal to'), ('Greater than or equal to', 'Greater than or equal to'), ('Greater than', 'Greater than')], default='Equal to', max_length=100),
        ),
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable?')),
                ('device_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicestate')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
