arch:
    - arm64

env:
    # https://packages.ubuntu.com/xenial/crossbuild-essential-armhf
    - CC=arm-linux-gnueabihf-gcc
    - SETARCH="setarch linux32 --verbose --32bit"

language: 
    - python

python: 
    - "3.9"

services:
    - docker

before_install:
- sudo dpkg --add-architecture armhf
- sudo apt-get update -yq
# There is no gcc-multilib on arm64.
# https://packages.ubuntu.com/xenial/gcc-multilib
# To run bin/hello, we need libc6:armhf deb package.
# Check `ldd bin/hello`.
# https://askubuntu.com/questions/133389
- |-
    sudo apt-get -yq install \
    crossbuild-essential-armhf \
    libc6:armhf



before_script:
    - pip install docker-compose

script:
    - docker-compose run --rm web flake8
    - docker-compose run --rm web pytest .

after_success:
    - docker-compose run --rm web codecov --token=${CODECOV_TOKEN}