os: linux
dist: xenial

language: 
    - python

python: 
    - "3.7"

services:
    - docker

before_script:
    - pip install docker-compose

script:
    - docker-compose -f docker-compose.ci.yml run --rm pytest

after_success:
    - docker-compose run web codecov --token=${CODECOV_TOKEN}