language: 
    - python

python: 
    - "3.7"

services:
    - docker

before_script:
    - pip install docker-compose
    - sleep 15

script:
    - docker-compose run --rm web pytest . -p no:warnings

after_success:
    - docker-compose run web codecov --token=${CODECOV_TOKEN}