arch:
    - arm64

language: 
    - python

python: 
    - "3.9"

services:
    - docker

before_script:
    - pip install docker-compose

script:
    - docker-compose run --rm web flake8
    - docker-compose run --rm web pytest .

after_success:
    - docker-compose run --rm web codecov --token=${CODECOV_TOKEN}