language: 
    - python

python: 
    - "3.7"

services:
    - docker

before_script:
    - pip install docker-compose

script:
    # - docker-compose run web flake8
    - docker-compose run --rm web pytest . -p no:warnings

after_success:
    - docker-compose run web codecov --token=${CODECOV_TOKEN}