dist: focal
os: linux
arch: arm64
# https://packages.ubuntu.com/focal/crossbuild-essential-armhf
compiler: arm-linux-gnueabihf-gcc
env:
    - SETARCH="setarch linux32 --verbose --32bit"
install:
    - sudo dpkg --add-architecture armhf
    - sudo apt-get update -yq
    # There is no gcc-multilib on arm64.
    # https://packages.ubuntu.com/focal/gcc-multilib
    # To run bin/hello, we need libc6:armhf deb package.
    # Check `ldd bin/hello`.
    # https://askubuntu.com/questions/133389
    - |-
        sudo apt-get -yq install \
        crossbuild-essential-armhf \
        libc6:armhf

# language: 
#     - python

# python: 
#     - "3.9"

services:
    - docker





before_script:
    - pip install docker-compose

script:
    - docker-compose run --rm web flake8
    - docker-compose run --rm web pytest .

after_success:
    - docker-compose run --rm web codecov --token=${CODECOV_TOKEN}