# dist: focal
language: c
arch: arm64
os: linux

env:
    - DOCKER_COMPOSE_VERSION=3.3

addons:
    apt:
        sources:
            - sourceline: "deb http://ftp.de.debian.org/debian stable main"

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get install --allow-unauthenticated -y wait-for-it binutils gdal-bin libproj-dev postgis* graphviz graphviz-dev
    - docker-compose build

script:
    # - $SETARCH
    # - docker-compose run --rm web flake8
    - docker-compose run --rm web pytest .

after_success:
    - docker-compose run --rm web codecov --token=${CODECOV_TOKEN}