# dist: focal
language: c
arch: arm64
os: linux

before_install:
    - docker-compose build

script:
    # - $SETARCH
    # - docker-compose run --rm web flake8
    - docker-compose run --rm web pytest .

after_success:
    - docker-compose run --rm web codecov --token=${CODECOV_TOKEN}