version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smarthub
      - POSTGRES_USER=smarthub
      - POSTGRES_PASSWORD=smarthub
  web:
    build: .
    command: python smarthub/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME:?POSTGRES_DB_NAME}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER:?POSTGRES_DB_USER}
      - POSTGRES_DB_PASS=${POSTGRES_DB_PASS:?POSTGRES_DB_PASS}