services:
  db:
    build: ./docker/postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  memcached:
    image: memcached:alpine
    ports:
      - 11211:11211
    command: 
      - "memcached"
  web:
    build: .
    command: bash -c "wait-for-it db:5432 -- wait-for-it memcached:11211 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - memcached
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - MQTT_QOS=$MQTT_QOS
      - MQTT_SERVER=$MQTT_SERVER
      - MQTT_BASE_TOPIC=$MQTT_BASE_TOPIC
      - MQTT_CLIENT_NAME=$MQTT_CLIENT_NAME
      