services:
  db:
    build:
      args:
        - ARCH_IMAGE=${ARCH_IMAGE:-arm32v7/postgres}
      context: . 
      dockerfile: ./docker/postgres/Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=smarthub
      - POSTGRES_PASSWORD=smarthub
      - AMD64=${ARCH_IMAGE}
  pytest:
    build: .
    command: bash -c "wait-for-it db:5432 -- pytest . -p no:warnings"
    volumes:
      - .:/code
    depends_on:
      - db