# Generated by Django 3.2.5 on 2021-08-10 14:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_auto_20210809_1510"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicelocation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="device",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="devicelocation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
