version: "3.9"
   
services:
  db:
    image: postgis/postgis
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}