# Generated by Django 3.2.5 on 2021-08-10 14:40

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Models = [
        apps.get_model("devices", "Device"),
        apps.get_model("devices", "DeviceLocation"),
    ]
    for MyModel in Models:
        for row in MyModel.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_auto_20210810_1436"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
