# Generated by Django 3.2.5 on 2021-08-10 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_auto_20210810_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name="devicelocation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
