# Generated by Django 3.2.5 on 2021-08-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20210810_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.devicelocation'),
        ),
    ]
