# Generated by Django 3.2.5 on 2021-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20210818_1149'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='user_device',
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location name'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'device_identifier'), name='user_device_identifier'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'friendly_name'), name='user_device_friendly_name'),
        ),
    ]
