# Generated by Django 3.2.5 on 2021-09-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_devicestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name you want to save this state under'),
        ),
    ]
